//.................................................................................................................................................................................................
//.............TTTTTTTTTTTTTTTRRRRRRRRRRRRR........AAAAAAA.......BBBBBBBBBBBBB........AAAAAA.......LLLLL..........HHHHH.....HHHHH......AAAAAAA....AAATTTTTTTTTTTT...OOOOOOOOOO......OORRRRRRRRRRR..
//............TTTTTTTTTTTTTTTRRRRRRRRRRRRRR.......AAAAAAA.......BBBBBBBBBBBBBB......AAAAAAAA......LLLLL..........HHHHH.....HHHHH......AAAAAAA....AAATTTTTTTTTTTT..OOOOOOOOOOOOO....OORRRRRRRRRRRR..
//...........TTTTTTTTTTTTTTTRRRRRRRRRRRRRRR.....AAAAAAAA.......BBBBBBBBBBBBBB......AAAAAAAA......LLLLL..........HHHHH.....HHHHH.....AAAAAAAA....AAATTTTTTTTTTTT.TOOOOOOOOOOOOOO...OORRRRRRRRRRRRR..
//...............TTTTT.....RRRRR....RRRRRR.....AAAAAAAAA......BBBB....BBBBBBB.....AAAAAAAAA.....LLLLL..........HHHHH.....HHHHH.....AAAAAAAAA........TTTTT.....TTOOOOOO.OOOOOOO...OORRR...RRRRRRR...
//..............TTTTT.....RRRRR.....RRRRR.....AAAAAAAAA......BBBB......BBBBB....AAAAAAAAAA.....LLLLL..........HHHHH.....HHHHH.....AAAAAAAAA........TTTTT.....TTOOOO.....OOOOOO..OORRR.....RRRRR....
//.............TTTTT.....RRRRR.....RRRRR....AAAAAAAAAAA.....BBBB......BBBBB....AAAAAAAAAA.....LLLLL..........HHHHH.....HHHHH....AAAAAAAAAAA.......TTTTT....TTTOOO......OOOOOO..OORRR.....RRRRR.....
//............TTTTT.....RRRRR...RRRRRRR....AAAAA.AAAAA.....BBBB....BBBBBB.....AAAAAAAAAAA....LLLLL..........HHHHH.....HHHHH....AAAAA.AAAAA.......TTTTT....TTTOOO.......OOOOO..OORRR...RRRRRRR......
//...........TTTTT.....RRRRRRRRRRRRRRR...AAAAAA.AAAAA.....BBBBBBBBBBBBBB....AAAAA..AAAAA....LLLLL..........HHHHHHHHHHHHHHH...AAAAAA.AAAAA.......TTTTT....TTTOO........OOOOO..OORRRRRRRRRRRR........
//..........TTTTT.....RRRRRRRRRRRRRR....AAAAA..AAAAAA....BBBBBBBBBBBBBB....AAAAA..AAAAA....LLLLL..........HHHHHHHHHHHHHHH...AAAAA..AAAAAA......TTTTT....TTTOO........OOOOO..OORRRRRRRRRRRR.........
//.........TTTTT.....RRRRRRRRRRRRR.....AAAAA...AAAAA....BBBBBBBBBBBBBBB...AAAAA...AAAAA...LLLLL..........HHHHHHHHHHHHHHH...AAAAA...AAAAA......TTTTT....TTTOO........OOOOO..OORRRRRRRRRR............
//........TTTTT.....RRRRRRRRRRRRR....AAAAAAAAAAAAAA....BBBB....BBBBBBB..AAAAAAAAAAAAAA...LLLLL..........HHHHH.....HHHHH..AAAAAAAAAAAAAA......TTTTT....TTTOOO.......OOOOO..OORRRRRRRRRR.............
//.......TTTTT.....RRRRR..RRRRRR....AAAAAAAAAAAAAAA...BBBB......BBBBB..AAAAAAAAAAAAAAA..LLLLL..........HHHHH.....HHHHH..AAAAAAAAAAAAAAA.....TTTTT....TTTOOO......OOOOOO..OORRR..RRRRRR.............
//......TTTTT.....RRRRR...RRRRRR...AAAAAAAAAAAAAAA...BBBB......BBBBB..AAAAAAAAAAAAAAA..LLLLL..........HHHHH.....HHHHH..AAAAAAAAAAAAAAA.....TTTTT.....TTOOOO.....OOOOOO..OORRR..RRRRRRR.............
//.....TTTTT.....RRRRR....RRRRRR.RAAAAA.....AAAAAA..BBBB.....BBBBBB.BAAAAA.....AAAAA..LLLLL..........HHHHH.....HHHHH.HAAAAA.....AAAAAA....TTTTT.....TTOOOOOOOOOOOOOO...OORRR...RRRRRR..............
//....TTTTT.....RRRRR....RRRRRR.RAAAA......AAAAAA..BBBBBBBBBBBBBBB.BAAAA......AAAAAA.LLLLLLLLLLLLLL.HHHHH.....HHHHH.HAAAA......AAAAAA....TTTTT......TOOOOOOOOOOOOOO...OORRR....RRRRRR..............
//...TTTTT.....RRRRR.....RRRRRRRAAAA.......AAAAA..BBBBBBBBBBBBBB.BBAAAA.......AAAAA.LLLLLLLLLLLLLL.HHHHH.....HHHHH.HAAAA.......AAAAA....TTTTT.......OOOOOOOOOOOOO....OORRR.....RRRRR...............
//..TTTTT.....RRRRR.....RRRRRRRAAAA.......AAAAAA.BBBBBBBBBBBBB..BBAAAA.......AAAAA.LLLLLLLLLLLLLL.HHHHH.....HHHHHHHAAAA.......AAAAAA...TTTTT........OOOOOOOOOO......OORRR.....RRRRR................
//.................................................................................................................................................................................................

//.................................................................................................................................................................................................
#include "DigiMouse.h"
//.................................................................................................................................................................................................

//.................................................................................................................................................................................................
#ifndef __TRABALHATOR_
#define __TRABALHATOR_
#define VERSION "V0.1"
#define N_OF_DIMENSIONS 2
#define N_OF_STEPS 4
#define PIN_LED_ACTIVE 1
#define PIXELS 3
#define STEP_DELAY 25
#define MOUSE_PERIOD 150000 // 2.5min
#endif
//.................................................................................................................................................................................................

//.................................................................................................................................................................................................
bool enable = 1;
int pointArr[N_OF_STEPS][N_OF_DIMENSIONS] = {{0, PIXELS}, {PIXELS, 0}, {0, -PIXELS}, {-PIXELS,0}};
//.................................................................................................................................................................................................

//.................................................................................................................................................................................................
void setup() {
  // Pin config
  pinMode(PIN_LED_ACTIVE, OUTPUT);

  // Objects
  DigiMouse.begin();
  Serial.begin(9600);
}
//.................................................................................................................................................................................................

//.................................................................................................................................................................................................
void loop() {
  // Device enable led
  digitalWrite(PIN_LED_ACTIVE, enable);
  
  // Plot
  if (enable){
    for(int i=0;i<(N_OF_STEPS);i++){
      DigiMouse.move(pointArr[i][0], pointArr[i][1], 0); // Plot
      DigiMouse.delay(STEP_DELAY); // Delay between steps
    }
    DigiMouse.delay(MOUSE_PERIOD); //Delay between sequences
  }
}
//.................................................................................................................................................................................................
